#!/bin/bash
src=$1
srcdir=./frontend
dstdir=./backend/static
thirdparty=$srcdir/3rdparty
setup=./setup.pyo
cssc=./cssc.jar
jsc=./jsc.jar
ext3=zepto,underscore,ink,backbone,typeahead
int3=ink
cd `dirname $0`
if [ '0' == "$3" ]; then opt=-O; fi
if [ '@' == "$4" ]; then dep=--depurar; fi

fc_less () {
  echo Compilando $src.less
  python -O $setup $srcdir/$src.less --salida $dstdir/ $opt --internas $int3 --3rdparty $thirdparty --compresor_css $cssc
}

fc_ls () {
  echo Compilando $src.ls
  if [ none != "$1" ]; then pext="--externas $ext3"; fi  # if [ none == "$1" ]; then pext=; else int="--internas prelude"; fi
  python -O $setup $srcdir/$src.ls --salida $dstdir/ $pext $opt --3rdparty $thirdparty --compresor_js $jsc $int $dep
}

fc_ll () {
  case $1 in
  less) fc_less ;;
  ls)   fc_ls   ;;
  esac
  ALL=$1
  if [ "0" == "$1" ]; then opt=-O; ALL=; fi
  if [ "" == "$ALL" ]; then fc_less; fc_ls; fi
}

case $src in

signin)
  SALL=$2
  if [ "0" == "$2" ]; then opt=-O; SALL=; fi
  if [ "" == "$SALL" ]; then fc_ll; elif [ ls == "$2" ]; then fc_ls none; else fc_less; fi
  ;;
customer-form)
  fc_ll $2
  ;;
dashboard)
  fc_ll $2
  ;;
all)
  ext4=$ext3
  ext3=''
  if [ '0' == "$2" ]; then opt=-O; fi
  src=signin
  fc_less
  fc_ls none
  ext3=$ext4
  src=customer-form
  fc_ll
  src=dashboard
  fc_ll
  ;;
*)
  echo Error: No existe \"$1\""  " .less"  ".ls
  ;;
esac
