application: plaft-sw
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /gz.appcache
  static_files: static/gz.appcache
  mime_type: text/cache-manifest
  upload: static/gz.appcache

- url: .*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: latest
